GET http://localhost:5000/api/books

###
POST http://localhost:5000/api/users/logIn
Content-Type: application/json

{
  "id": "jww0418",
  "password": "123"
}

###
POST  http://localhost:5000/api/users/signUpChecker
Content-Type: application/json

{
  "id": "newID"
}

###
POST http://localhost:5000/api/users/signUp
Content-Type: application/json

{
  "name": "chansol",
  "id": "sol1234",
  "password": "1234",
  "isAdmin": false,
  "phone": "010-3879-7817",
  "gender": "female",
  "yyyy": "2000",
  "mm": "10",
  "dd": "24",
  "email": "chansol1024@naver.com"
}

###
GET http://localhost:5000/api/books?writer=123

###
GET http://localhost:5000/api/books?all=인간&limit=3
###
GET http://localhost:5000/api/books/subject?subNum=1&limit=3&cursor=6217731f60c9f772762328fa
###
GET http://localhost:5000/api/books/detailed?title=Do&writer=경&isbn=&publisher=&limit=3
###
GET http://localhost:5000/api/users/checkLogIn
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE1MGM4NDg1ZjY4ODg5OGY5ZWUyMTYiLCJuYW1lIjoid29ud29vIiwiZW1haWwiOiJqd3cwNDE4QG5hdmVyLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NTY0MTkxNiwiZXhwIjoxNjQ1OTAxMTE2fQ.mEmFQ3DeK0BBzAs2WKSYNXGV8Ju2f_947jA_JTNlwm0
###
PUT http://localhost:5000/api/users/interestingBookUpdate
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFhNmM5OTIyZTFiMDgwMzg5NTU1NDUiLCJuYW1lIjoid29ud29vIiwiZW1haWwiOiJqd3cwNDE4QG5hdmVyLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NTk3NjUyOCwiZXhwIjoxNjQ2MjM1NzI4fQ.zUbZHOern0kR4gv146x0LpkG1vWtXFLACgq6a1k2h00",

  "interestingBooks": "62191d387d697cc5c0dad552"
}
###
PUT http://localhost:5000/api/users/userUpdate
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFhNmM5OTIyZTFiMDgwMzg5NTU1NDUiLCJuYW1lIjoid29ud29vIiwiZW1haWwiOiJqd3cwNDE4QG5hdmVyLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NjI0NDg5MywiZXhwIjoxNjQ2NTA0MDkzfQ.Mbfk8x8B0afbKFcU8gD2-sWcYU7pxsz02EJQawWfk6s",
  "yyyy": "2001"
}